-- Generated by scripts/gen-users-d1-schema.py from supabase/schema.sql. Do not edit by hand.

CREATE TABLE IF NOT EXISTS cyn_members (
  openfront_id TEXT PRIMARY KEY,
  in_game_name TEXT NOT NULL,
  timezone TEXT NOT NULL,
  discord_username TEXT,
  nationality TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  user_id TEXT,
  discord_user_id TEXT,
  claimed INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS cyn_speedruns (
  openfront_id TEXT PRIMARY KEY,
  game_id TEXT NOT NULL,
  seconds INTEGER NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 1,
  submitted_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  tiles3min_percent REAL
);

CREATE TABLE IF NOT EXISTS cyn_bumps (
  openfront_id TEXT PRIMARY KEY,
  bump_count INTEGER NOT NULL DEFAULT 0,
  last_bump_at TEXT
);

CREATE TABLE IF NOT EXISTS cyn_event_admins (
  discord_username TEXT PRIMARY KEY,
  user_id TEXT
);

CREATE TABLE IF NOT EXISTS cyn_event_teams (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  event_id TEXT NOT NULL,
  name TEXT NOT NULL,
  starting_points INTEGER NOT NULL DEFAULT 0,
  captain TEXT,
  players TEXT NOT NULL DEFAULT '{}',
  UNIQUE (event_id, name)
);

CREATE TABLE IF NOT EXISTS cyn_event_submissions (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  event_id TEXT NOT NULL,
  team_id TEXT NOT NULL,
  submitted_by TEXT NOT NULL,
  game_link TEXT NOT NULL,
  screenshot_url TEXT NOT NULL,
  category TEXT NOT NULL,
  points INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  reviewed_by TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  reviewed_at TEXT
);

CREATE TABLE IF NOT EXISTS cyn_xp (
  openfront_id TEXT PRIMARY KEY,
  xp INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cyn_quest_claims (
  openfront_id TEXT NOT NULL,
  quest_id TEXT NOT NULL,
  claim_date TEXT NOT NULL,
  claimed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (openfront_id, quest_id, claim_date)
);

CREATE TABLE IF NOT EXISTS cyn_game_tile_stats (
  game_id TEXT NOT NULL,
  vendored_commit TEXT NOT NULL,
  compute_logic_version INTEGER NOT NULL,
  max_tiles TEXT NOT NULL,
  max_percent TEXT NOT NULL,
  final_tiles TEXT NOT NULL,
  computed_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (game_id, vendored_commit, compute_logic_version)
);

CREATE TABLE IF NOT EXISTS cyn_help_conversations (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  visitor_key TEXT NOT NULL,
  display_name TEXT,
  status TEXT NOT NULL DEFAULT 'open',
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_help_messages (
  id TEXT PRIMARY KEY DEFAULT (lower(hex(randomblob(16)))),
  conversation_id TEXT NOT NULL,
  role TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_help_rate_limit (
  rate_key TEXT PRIMARY KEY,
  window_start TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  count INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS cyn_member_snapshots (
  openfront_id TEXT NOT NULL,
  snapshot_date TEXT NOT NULL,
  elo INTEGER,
  all_wins INTEGER NOT NULL DEFAULT 0,
  xp INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  elo_2v2 INTEGER,
  PRIMARY KEY (openfront_id, snapshot_date)
);

CREATE TABLE IF NOT EXISTS cyn_chat_moderators (
  discord_username TEXT PRIMARY KEY,
  user_id TEXT
);

CREATE TABLE IF NOT EXISTS cyn_clan_chat_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_user_id TEXT NOT NULL,
  author_openfront_id TEXT NOT NULL,
  author_name TEXT NOT NULL,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_chat_message_counts (
  openfront_id TEXT PRIMARY KEY,
  count INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cyn_supporters (
  openfront_id TEXT PRIMARY KEY,
  added_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_inner_circle (
  openfront_id TEXT PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS cyn_metrics_daily (
  day TEXT PRIMARY KEY,
  member_count INTEGER,
  presence_count INTEGER,
  vc_active_member_ids TEXT NOT NULL DEFAULT '[]',
  vc_total_minutes INTEGER NOT NULL DEFAULT 0,
  public_messages INTEGER NOT NULL DEFAULT 0,
  private_messages INTEGER NOT NULL DEFAULT 0,
  discord_joins_today INTEGER NOT NULL DEFAULT 0,
  clan_registrations_today INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_metrics_channel_state (
  channel_id TEXT PRIMARY KEY,
  last_message_id TEXT,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_site_visits (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  visited_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  is_member INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS cyn_survey_responses (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id TEXT NOT NULL UNIQUE,
  in_game_name TEXT NOT NULL,
  discord_username TEXT,
  answers TEXT NOT NULL,
  comment TEXT,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_kudos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  game_id TEXT NOT NULL,
  from_openfront_id TEXT NOT NULL,
  to_openfront_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  emoji TEXT NOT NULL DEFAULT '🎉',
  UNIQUE (game_id, from_openfront_id, to_openfront_id, emoji)
);

CREATE TABLE IF NOT EXISTS cyn_game_nights (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  starts_at TEXT NOT NULL,
  note TEXT,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_game_night_rsvps (
  game_night_id INTEGER NOT NULL,
  openfront_id TEXT NOT NULL,
  status TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now')),
  PRIMARY KEY (game_night_id, openfront_id)
);

CREATE TABLE IF NOT EXISTS cyn_member_discord_status (
  openfront_id TEXT PRIMARY KEY,
  in_guild INTEGER NOT NULL,
  has_cyn_role INTEGER NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ','now'))
);

CREATE TABLE IF NOT EXISTS cyn_ranked_matches (
  game_id TEXT NOT NULL,
  ladder TEXT NOT NULL,
  ended_at TEXT NOT NULL,
  duration_s INTEGER,
  map TEXT,
  top_count INTEGER NOT NULL DEFAULT 0,
  players TEXT NOT NULL DEFAULT '[]',
  PRIMARY KEY (game_id)
);

CREATE TABLE IF NOT EXISTS auth_users (
  id TEXT PRIMARY KEY,
  discord_user_id TEXT,
  created_at TEXT,
  last_sign_in_at TEXT
);
