// Generated by scripts/gen-users-d1-schema.py. Do not edit by hand.
export const USERS_META = {
  "cyn_members": {
    "json": [],
    "bool": [
      "claimed"
    ],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "in_game_name",
      "timezone",
      "discord_username",
      "nationality",
      "created_at",
      "updated_at",
      "user_id",
      "discord_user_id",
      "claimed"
    ]
  },
  "cyn_speedruns": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "game_id",
      "seconds",
      "attempts",
      "submitted_at",
      "tiles3min_percent",
      "verified"
    ]
  },
  "cyn_bumps": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "bump_count",
      "last_bump_at"
    ]
  },
  "cyn_event_admins": {
    "json": [],
    "bool": [],
    "pk": [
      "discord_username"
    ],
    "cols": [
      "discord_username",
      "user_id"
    ]
  },
  "cyn_event_teams": {
    "json": [
      "players"
    ],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "event_id",
      "name",
      "starting_points",
      "captain",
      "players"
    ]
  },
  "cyn_event_submissions": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "event_id",
      "team_id",
      "submitted_by",
      "game_link",
      "screenshot_url",
      "category",
      "points",
      "status",
      "reviewed_by",
      "created_at",
      "reviewed_at"
    ]
  },
  "cyn_xp": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "xp"
    ]
  },
  "cyn_quest_claims": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id",
      "quest_id",
      "claim_date"
    ],
    "cols": [
      "openfront_id",
      "quest_id",
      "claim_date",
      "claimed_at"
    ]
  },
  "cyn_game_tile_stats": {
    "json": [
      "max_tiles",
      "max_percent",
      "final_tiles"
    ],
    "bool": [],
    "pk": [
      "game_id",
      "vendored_commit",
      "compute_logic_version"
    ],
    "cols": [
      "game_id",
      "vendored_commit",
      "compute_logic_version",
      "max_tiles",
      "max_percent",
      "final_tiles",
      "computed_at"
    ]
  },
  "cyn_help_conversations": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "visitor_key",
      "display_name",
      "status",
      "created_at",
      "updated_at"
    ]
  },
  "cyn_help_messages": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "conversation_id",
      "role",
      "content",
      "image_url",
      "created_at"
    ]
  },
  "cyn_help_rate_limit": {
    "json": [],
    "bool": [],
    "pk": [
      "rate_key"
    ],
    "cols": [
      "rate_key",
      "window_start",
      "count"
    ]
  },
  "cyn_member_snapshots": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id",
      "snapshot_date"
    ],
    "cols": [
      "openfront_id",
      "snapshot_date",
      "elo",
      "all_wins",
      "xp",
      "created_at",
      "elo_2v2"
    ]
  },
  "cyn_chat_moderators": {
    "json": [],
    "bool": [],
    "pk": [
      "discord_username"
    ],
    "cols": [
      "discord_username",
      "user_id"
    ]
  },
  "cyn_clan_chat_messages": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "author_user_id",
      "author_openfront_id",
      "author_name",
      "content",
      "created_at"
    ]
  },
  "cyn_chat_message_counts": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "count"
    ]
  },
  "cyn_supporters": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "added_at"
    ]
  },
  "cyn_inner_circle": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id"
    ]
  },
  "cyn_metrics_daily": {
    "json": [
      "vc_active_member_ids"
    ],
    "bool": [],
    "pk": [
      "day"
    ],
    "cols": [
      "day",
      "member_count",
      "presence_count",
      "vc_active_member_ids",
      "vc_total_minutes",
      "public_messages",
      "private_messages",
      "discord_joins_today",
      "clan_registrations_today",
      "updated_at"
    ]
  },
  "cyn_metrics_channel_state": {
    "json": [],
    "bool": [],
    "pk": [
      "channel_id"
    ],
    "cols": [
      "channel_id",
      "last_message_id",
      "updated_at"
    ]
  },
  "cyn_site_visits": {
    "json": [],
    "bool": [
      "is_member"
    ],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "visited_at",
      "is_member"
    ]
  },
  "cyn_survey_responses": {
    "json": [
      "answers"
    ],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "user_id",
      "in_game_name",
      "discord_username",
      "answers",
      "comment",
      "created_at",
      "updated_at"
    ]
  },
  "cyn_kudos": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "game_id",
      "from_openfront_id",
      "to_openfront_id",
      "created_at",
      "emoji"
    ]
  },
  "cyn_game_nights": {
    "json": [],
    "bool": [],
    "pk": [
      "id"
    ],
    "cols": [
      "id",
      "starts_at",
      "note",
      "created_by",
      "created_at"
    ]
  },
  "cyn_game_night_rsvps": {
    "json": [],
    "bool": [],
    "pk": [
      "game_night_id",
      "openfront_id"
    ],
    "cols": [
      "game_night_id",
      "openfront_id",
      "status",
      "updated_at"
    ]
  },
  "cyn_member_discord_status": {
    "json": [],
    "bool": [
      "in_guild",
      "has_cyn_role"
    ],
    "pk": [
      "openfront_id"
    ],
    "cols": [
      "openfront_id",
      "in_guild",
      "has_cyn_role",
      "updated_at"
    ]
  },
  "cyn_saved_games": {
    "json": [],
    "bool": [],
    "pk": [
      "openfront_id",
      "game_id"
    ],
    "cols": [
      "openfront_id",
      "game_id",
      "title",
      "saved_at"
    ]
  },
  "cyn_ranked_matches": {
    "json": [
      "players"
    ],
    "bool": [],
    "pk": [
      "game_id"
    ],
    "cols": [
      "game_id",
      "ladder",
      "ended_at",
      "duration_s",
      "map",
      "top_count",
      "players"
    ]
  }
}
