"""Translate the user-data tables of supabase/schema.sql into a SQLite (D1) schema.

Output: worker/d1/users-schema.sql. Checks, foreign keys and RLS are dropped on purpose - the Worker API enforces
access rules in code. Run: python scripts/gen-users-d1-schema.py
"""
import re
import pathlib

root = pathlib.Path(__file__).resolve().parent.parent
src = (root / 'supabase' / 'schema.sql').read_text(encoding='utf-8')

# Already live in the hot D1 database (cynosure-hot) or pure caches.
SKIP = {
    'cyn_member_games_cache', 'cyn_game_detail_cache', 'cyn_roster_cache', 'cyn_clan_score_ledger',
}

NOW = "(strftime('%Y-%m-%dT%H:%M:%fZ','now'))"
UUID = "(lower(hex(randomblob(16))))"


def strip_comments(s):
    return re.sub(r'--[^\n]*', '', s)


def split_top(s):
    out, depth, cur = [], 0, ''
    for ch in s:
        if ch == '(':
            depth += 1
        elif ch == ')':
            depth -= 1
        if ch == ',' and depth == 0:
            out.append(cur.strip())
            cur = ''
        else:
            cur += ch
    if cur.strip():
        out.append(cur.strip())
    return out


def sql_type(t):
    t = t.lower()
    if t in ('integer', 'int', 'bigint', 'boolean', 'smallint'):
        return 'INTEGER'
    if t.startswith('numeric') or t in ('real', 'double'):
        return 'REAL'
    return 'TEXT'


def convert_default(d):
    d = d.strip()
    if d in ('now()', 'timezone(\'utc\', now())'):
        return NOW
    if d == 'gen_random_uuid()':
        return UUID
    if d == 'true':
        return '1'
    if d == 'false':
        return '0'
    m = re.match(r"^'(.*)'(::\w+(\[\])?)?$", d)
    if m:
        return "'" + m.group(1) + "'"
    if re.match(r'^-?\d+(\.\d+)?$', d):
        return d
    return None


tables = {}
order = []
for m in re.finditer(r'create table if not exists public\.(\w+)\s*\((.*?)\n\);', src, re.S | re.I):
    name, body = m.group(1), strip_comments(m.group(2))
    if name in SKIP:
        continue
    cols, pk, uniques = [], [], []
    for part in split_top(body):
        low = part.lower()
        if low.startswith('primary key'):
            pk = [c.strip() for c in re.search(r'\((.*)\)', part).group(1).split(',')]
            continue
        if low.startswith('unique'):
            uniques.append([c.strip() for c in re.search(r'\((.*)\)', part).group(1).split(',')])
            continue
        if low.startswith(('check', 'constraint', 'foreign')):
            continue
        cm = re.match(r'^(\w+)\s+([\w\[\]]+(?:\(\d+(?:,\d+)?\))?)(.*)$', part, re.S)
        if not cm:
            print('skip part', name, part[:60])
            continue
        col, typ, rest = cm.group(1), cm.group(2), cm.group(3)
        cols.append({'name': col, 'type': typ, 'rest': rest})
    tables[name] = {'cols': cols, 'pk': pk, 'uniques': uniques}
    order.append(name)

# ALTER TABLE ... ADD COLUMN
for m in re.finditer(r'alter table public\.(\w+) add column if not exists (\w+) ([\w\[\]]+)([^;]*);', src, re.I):
    t, col, typ, rest = m.groups()
    if t in tables and not any(c['name'] == col for c in tables[t]['cols']):
        tables[t]['cols'].append({'name': col, 'type': typ, 'rest': rest})
# the kudos table got a wider unique key
if 'cyn_kudos' in tables:
    tables['cyn_kudos']['uniques'] = [['game_id', 'from_openfront_id', 'to_openfront_id', 'emoji']]

out = ['-- Generated by scripts/gen-users-d1-schema.py from supabase/schema.sql. Do not edit by hand.', '']
for name in order:
    t = tables[name]
    lines = []
    ident_pk = None
    for c in t['cols']:
        rest = c['rest']
        low = rest.lower()
        typ = sql_type(c['type'])
        if 'generated always as identity' in low or 'generated by default as identity' in low:
            ident_pk = c['name']
            lines.append(f"  {c['name']} INTEGER PRIMARY KEY AUTOINCREMENT")
            continue
        piece = f"  {c['name']} {typ}"
        if 'primary key' in low:
            piece += ' PRIMARY KEY'
            t['pk'] = []
        if 'not null' in low:
            piece += ' NOT NULL'
        if re.search(r'\bunique\b', low) and 'primary key' not in low:
            piece += ' UNIQUE'
        dm = re.search(r'default\s+((?:\'[^\']*\'(?:::\w+(?:\[\])?)?)|(?:[\w.]+\([^)]*\))|(?:[^\s,]+))', rest, re.I)
        if dm:
            d = convert_default(dm.group(1))
            if d is not None:
                piece += f' DEFAULT {d}'
        lines.append(piece)
    if t['pk']:
        lines.append(f"  PRIMARY KEY ({', '.join(t['pk'])})")
    for u in t['uniques']:
        lines.append(f"  UNIQUE ({', '.join(u)})")
    out.append(f"CREATE TABLE IF NOT EXISTS {name} (")
    out.append(',\n'.join(lines))
    out.append(');')
    out.append('')

# Supabase auth users, reduced to what the migration needs (no emails).
out.append('''CREATE TABLE IF NOT EXISTS auth_users (
  id TEXT PRIMARY KEY,
  discord_user_id TEXT,
  created_at TEXT,
  last_sign_in_at TEXT
);
''')

dest = root / 'worker' / 'd1'
dest.mkdir(parents=True, exist_ok=True)
(dest / 'users-schema.sql').write_text('\n'.join(out), encoding='utf-8')
print(len(order), 'tables ->', dest / 'users-schema.sql')
print(' '.join(order))

# Column kinds the Worker needs to turn D1 TEXT/INTEGER back into JSON / booleans, plus primary keys for upserts.
import json
meta = {}
for name in order:
    t = tables[name]
    json_cols = [c['name'] for c in t['cols'] if c['type'].lower() in ('jsonb', 'json') or c['type'].endswith('[]')]
    bool_cols = [c['name'] for c in t['cols'] if c['type'].lower() == 'boolean']
    pk = list(t['pk'])
    if not pk:
        for c in t['cols']:
            low = c['rest'].lower()
            if 'primary key' in low or 'generated always as identity' in low:
                pk = [c['name']]
                break
    meta[name] = {'json': json_cols, 'bool': bool_cols, 'pk': pk, 'cols': [c['name'] for c in t['cols']]}
js = '// Generated by scripts/gen-users-d1-schema.py. Do not edit by hand.\nexport const USERS_META = ' + json.dumps(meta, indent=2) + '\n'
(dest / 'usersMeta.js').write_text(js, encoding='utf-8')
print('meta ->', dest / 'usersMeta.js')
